javascripts:
  top:
    - public/javascripts/jquery-1.4.1.min.js
  bottom:
    - public/javascripts/jquery.watermark.js
    - public/javascripts/application.js
    - public/javascripts/drop_down.js
    - public/javascripts/jquery.tipTip.min.js
    - public/javascripts/flash_hider.js
  home:
    - public/javascripts/map_shrinker.js
  listings:
    - public/javascripts/twidget.js
  edit:
    - public/javascripts/checkbox.js
    - public/javascripts/jquery.auto-geocoder.js

stylesheets:
  common:
    - public/stylesheets/reset.css
    - public/stylesheets/960.css
    - public/stylesheets/layout.css
    - public/stylesheets/bubble.css
    - public/stylesheets/tipTip.css
    - public/stylesheets/forum.css
    - public/stylesheets/formtastic.css
    - public/stylesheets/formtastic_changes.css
  listings:
    - public/stylesheets/checkbox.css